version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: learning-db
    environment:
      POSTGRES_DB: learning_db1
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - learning-network

  learning-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: learning-service-app
    ports:
      - "8090:8090"
    environment:
      SERVER_PORT: 8090
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/learning_db1
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_FLYWAY_ENABLED: false
      JWT_SECRET: myVeryLongSecretKeyThatIsAtLeast257BitsLongForJWTHMACSignatureAlgorithmSecurity
      JWT_EXPIRATION: 86400000
      SPRING_MAIL_HOST: smtp.gmail.com
      SPRING_MAIL_PORT: 587
      SPRING_MAIL_USERNAME: hajerhajmeftah343@gmail.com
      SPRING_MAIL_PASSWORD: xkyt uuew rbkp qpoe
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: true
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: true
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_REQUIRED: true
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_SSL_TRUST: smtp.gmail.com
      APP_EMAIL_FROM: hajerhajmeftah343@gmail.com
      APP_EMAIL_FROM_NAME: Coding Factory Learning Platform
      APP_BASE_URL: http://localhost:4200
      STRIPE_API_KEY: sk_test_51RP7SIRslzO02W4LAXedv7JzYfdnKN9zAYGuQhOCV2O6gfSx17i2LEVb49B2I4y8zo7D1e3jhq1VtrrO2zi45Z7B00CjZm6T9W
      STRIPE_PUBLISHABLE_KEY: pk_test_51RP7SIRslzO02W4LkMzYpSIW5GNkLvUDQpWSAy4zUQiloVqNwSNn5JMSVbtQkPI7717EaFH3RUEX6hxWu0cj7Ocl00lxUjVsTM
      OPENAI_API_KEY: 
      MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: health,info,prometheus
      MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS: when-authorized
      MANAGEMENT_ENDPOINTS_WEB_BASE_PATH: /actuator
      MANAGEMENT_ENDPOINT_PROMETHEUS_ENABLED: true
      MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED: true
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./uploads:/app/uploads
    networks:
      - learning-network

volumes:
  postgres_data:
    driver: local

networks:
  learning-network:
    driver: bridge
